version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sensorReadings

  api:
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --workers 8
    depends_on:
      - db
    restart: always
    ports:
      - 8001:8001 
    expose: 
      - 8001
    environment:
      - APP_PORT=8001
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/sensorReadings

  dashboard:
    build: ./dashboard
    command: streamlit run app/app.py --server.port 8002
    depends_on: 
      - db
      - api 
    restart: always 
    ports:
      - 8002:8002
    expose:
      - 8002 
    environment:
      - STREAMLIT_USER=${STREAMLIT_USER}
      - STREAMLIT_PASSWORD=${STREAMLIT_PASSWORD}
      - API_BASE_URL=${API_BASE_URL}

volumes:
  postgres_data:
