version: '3.1'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sensorReadings

  api:
    build: ./api
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - 8000:8000 
    expose: 
      - 8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sensorReadings

volumes:
  postgres_data:
